myName = input("What's you name? ")
myAge = input("How old are you? ")
print("Gee, that's REALLY OLD")
replit = input("Do you like Replit? ")
print("OF COURSE YOU DO!")

print()
print("So, you are")
print(myName)
print("and are the ripe old age of")
print(myAge)
print("and clearly think that Replit is")
print(replit)


my_variable = input("WHO GOES THERE? ")
print(my_variable)


myGrandma = input("How's your Grandma doing? 😘")
print(myGrandma)

myLunch = input("What are you having for lunch? ")
print("Hmm, it sounds like you really should just order")
print(myLunch)
print("as soon as possible!")


print("Definitely not a Phishing Scam")
print()
input("Your Name")
print("Thanks for logging in")
print(myName)
cardNumber = input("What is your credit card number?")
print("Thanks, I definitely wont put")
print(cardNumber)
print("into Amazon and order anything weird")
print()
print("Promise")
maidenName = input("What is your Mother's maiden name? ")
print()
print("That's cool, I just wanted to know that")
print(maidenName)
print("was your Mum's maiden name. Not because the bank requested it or anything, honest.")

Your_name = input("What's your name? ")
Your_food = input("What's your favourite food? ")
Your_music = input("What's your favourite music? ")
Your_place = input("Where do you live? ")  
print("Hi")
print(Your_name)
print(" I know that you like to eat")
print(Your_food)
print("and you like to listen to")
print(Your_music)
print("and you live in")
print(Your_place)
